# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).



user = User.create!(:name => "Charles Xavier", :email => "user@host.test", :password => "asdfasdf")

# Please keep these alphabetized.
skill_tags = ["Android", "C", "C++", "iOS", "Ruby", "Perl", "Python", "Ruby/Rails", "Node.js", "MySQL", "PostgreSQL", "MongoDB", "Redis", "RSpec", "Memcached"]
skill_tags.each do |tag|
  Tag::Skill.create!(:value => tag)
end

# Please keep these alphabetized.
industry_tags = ["Advertising", "Analytics", "Commerce", "Consulting", "Dating", "Education", "Energy", "Entertainment", "Environment", "Fashion", "Gaming", "Infrastructure", "Local", "Medical", "Mobile", "Music", "Nonprofit", "Political", "Recruiting", "Retail", "Social", "Security", "Travel", "Utility"]
industry_tags.each do |tag|
  Tag::Industry.create!(:value => tag)
end
# Please keep these sorted by level.
position_tags = ["Entry", "Junior", "Senior", "Lead", "Executive"]
position_tags.each do |tag|
  Tag::Position.create!(:value => tag)
end

user.skills << Tag::Skill.order("random()").limit(6)
user.industries << Tag::Industry.order("random()").limit(4)
user.positions << Tag::Position.order("random()").limit(2)

tag_proc = Proc.new { |tag_value|
  tag = Tag.find_by_value(tag_value)

  if tag.nil?
    raise Exception.new("Unable to find tag: #{tag_value}")
  end

  tag
}

companies = [
  { :name => "UniversityNow",
    :email => "kathleen@unow.com",
    :contact_name => "Kathleen",
    :description => "UniversityNow was built and supported by a team of visionaries who could see the future and believe in the right that everyone has to higher education. Learn more about the UniversityNow team.",
    :size => 40,
    :dev_team_size => 3,
    :industries => ["Social", "Education"],
    :requisitions => [ { :name => "Full-stack Ruby on Rails Developer",
                         :description => "We're looking for someone to take ownership across the board on various tasks.",
                         :skills => [ "Ruby/Rails", "PostgreSQL" ],
                         :positions => [ "Junior", "Senior" ]},
                        { :name => "QA Developer",
                          :description => "Love testing? We need someone to ensure our code goes out bug free!",
                          :skills => [ "Ruby/Rails", "RSpec", "PostgreSQL" ],
                          :positions => [ "Junior", "Senior" ] } ] },
  { :name => "Airbnb",
    :email => "kumi@airbnb.com",
    :contact_name => "Kumi Bailey", # Justin emailed on 1/16/2013
    :url => "https://www.airbnb.com/",
    :description => "P2P rentals.",
    :location => "Potrero",
    :industries => ["Travel", "Social"],
    :crunchbase_url => "http://www.crunchbase.com/company/airbnb",
    :requisitions => [ { :name => "TODO",
                         :description => "TODO",
                         :skills => [ "Ruby/Rails", "iOS", "Android" ],
                         :positions => [] } ] },
  { :name => "AliveCor",
    :email => "david@alivecor.com", # Justin has no connection
    :contact_name => "David Albert",
    :url => "www.alivecor.com",
    :description => "Trying to bring mobile tech to hospitals/healthcare, not yet cleared by FDA for US use - but okay for veterinary use ",
    :misc => "Getting second round funding soon",
    :location => "SF",
    :industries => ["Medical"],
    :crunchbase_url => "http://www.crunchbase.com/company/alivecor",
    :requisitions => [ { :name => "TODO",
                         :description => "TODO",
                         :skills => [ "Android", "iOS", "JavaScript", "HTML", "Ruby", "Python" ],
                         :positions => [] } ] },
  { :name => "Appdynamics",
    :email => "erowe@appdynamics.com",
    :contact_name => "Ed Rowe", # Justin has no connections
    :url => "http://www.appdynamics.com/",
    :description => "Java and .NET application performance management and monitoring",
    :location => "SF",
    :industries => ["Analytics", "Infrastructure"],
    :crunchbase_url => "http://www.crunchbase.com/company/appdynamics",
    :requisitions => [ { :name => "TODO",
                         :description => "TODO",
                         :skills => [ "Java", "C#", ".NET" ],
                         :positions => [] } ] },
  { :name => "Asana",
    :url => "http://www.asana.com/",
    :description => "Team workflow management",
    :location => "1550 Bryant Street, Suite 100, San Francisco, CA, 94103",
    :misc => "$10k hardware budget, 43 employees, 14 engineers, $38.4 million in funding, 401k, yoga, health, vision, dental, unlimited vacation",
    :email => "dustin@asana.com",
    :contact_name => "Dustin Moskovitz", # Justin has no connections
    :industries => ["Productivity"],
    :requisitions => [ { :name => "Software Engineer",
                         :description => "As a Software Engineer, you'll be building Asana's features end-to-end, from designing their data models to implementing the subtle interaction behaviors that differentiate good software and great software. Working closely with seasoned UI designers and supported by a world-class software-infrastructure team, you can focus on delighting users with both large new features and (thanks to our continuous deployment architecture) daily small product enhancements.",
                         :skills => [ "JavaScript", "HTML", "CSS" ],
                         :positions => ["Junior", "Senior"] },
                       { :name => "Data Infrastructure Engineer",
                         :description => "The Data Infrastructure Engineer is a critical role for Asana’s growth. As a key member of the engineering team, you will work closely with the product teams to build out and refine the infrastructure we use to gain insights from our data and evaluate our success. As our user base rapidly grows, you will architect and develop improvements to our data infrastructure, and design and implement data analysis tools that increase the scalability, accuracy and accessibility of our data to support ongoing product decisions.",
                         :skills => [ "SQL" ],
                         :positions => ["Senior"] } ] },
  { :name => "Bunchball",
    :email => "rajat@bunchball.com",
    :contact_name => "Rajat Paharia", # Justin's only connection is a girl he played tennis with twice
    :url => "http://www.bunchball.com/",
    :description => "Gamification platform sold to websites and businesses.",
    :location => "Redwood City",
    :industries => ["Gaming"],
    :crunchbase_url => "http://www.crunchbase.com/company/bunchball",
    :requisitions => [ { :name => "TODO",
                         :description => "TODO",
                         :skills => [ "Java" ],
                         :positions => [] } ] },
  { :name => "CardSpring",
    :email => "jeff@cardspring.com",
    :contact_name => "Jeff Winner", # Justin has no connections
    :url => "https://cardspring.com/",
    :description => "CardSpring is a simple API that lets developers add web and mobile applications like coupons, loyalty programs and digital receipts to payment cards.",
    :location => "SF, PA",
    :industries => ["Commerce"],
    :crunchbase_url => "http://www.crunchbase.com/company/cardspring",
    :requisitions => [ { :name => "TODO",
                         :description => "TODO",
                         :skills => [ "Ruby/Rails", "CoffeeScript", "Node.js" ],
                         :positions => [] } ] },
  { :name => "Climate Corporation",
    :email => "andy@climate.com",
    :contact_name => "Andy Mutz", # Justin LinkedIn'd Adeline Tai on 1/16/2013
    :url => "www.climate.com",
    :description => "Weather planning, management and insurance for companies",
    :location => "SF",
    :industries => ["Environment"],
    :crunchbase_url => "http://www.crunchbase.com/company/weatherbill",
    :requisitions => [ { :name => "TODO",
                         :description => "TODO",
                         :skills => [ "Ruby/Rails" ],
                         :positions => [] } ] },
  { :name => "CloudEra",
    :email => "amr@cloudera.com",
    :contact_name => "Amr Awadallah", # Justin has Ali and Chung: second-degree connections to CTO
    :url => "http://www.cloudera.com/",
    :description => "Cloudera develops open-source software for a world dependent on Big Data.",
    :location => "SF, PA",
    :industries => ["Infrastructure"],
    :crunchbase_url => "http://www.crunchbase.com/company/cloudera",
    :requisitions => [ { :name => "TODO",
                         :description => "TODO",
                         :skills => [ "Ruby/Rails", "Python", "JavaScript", "Hadoop" ],
                         :positions => [] } ] },
  { :name => "Coursera",
    :email => "ng@coursera.org",
    :contact_name => "Andrew Ng", # David Blake and Laura Powers know folks in BD
    :url => "https://www.coursera.org/about/jobs",
    :description => "Online free education",
    :location => "MV",
    :industries => ["Education"],
    :crunchbase_url => "http://www.crunchbase.com/company/coursera",
    :requisitions => [ { :name => "TODO",
                         :description => "TODO",
                         :skills => [ "AWS", "Memcached", "Python", "MongoDB", "SQL" ],
                         :positions => [] } ] },
  { :name => "Credo Mobile",
    :email => "swilliams@credomobile.com",
    :contact_name => "Simon Williams", # Justin has no connections
    :url => "http://www.credomobile.com/jobs/credo-jobs.aspx",
    :description => "Mobile technology... 'doing social good'.... maybe.",
    :misc => "Credit cards, mobile phones, lots of archaic shit, good for a graybeard who doesn't want new tech",
    :location => "SF",
    :industries => ["Mobile"],
    :crunchbase_url => "",
    :requisitions => [ { :name => "TODO",
                         :description => "TODO",
                         :skills => [ ".NET" ],
                         :positions => [] } ] },
  { :name => "Domo",
    :email => "daren.thayne@domo.com",
    :contact_name => "Daren Thayne", # Justin has no connections
    :url => "www.domo.com",
    :description => "",
    :stack => [],
    :misc => "just got $30M in funding",
    :location => "",
    :industries => [],
    :crunchbase_url => "http://www.crunchbase.com/company/domo-studios",
    :requisitions => [ { :name => "TODO",
                         :description => "TODO",
                         :skills => [],
                         :positions => [] } ] },
  { :name => "Dropcam",
    :email => "aamir@dropcam.com",
    :contact_name => "Aamir Virani", # Barry knows someone in marketing
    :url => "https://www.dropcam.com/",
    :description => "Security cam and app for mobile",
    :stack => ["python, c, ios, android"],
    :misc => "",
    :location => "SF",
    :industries => ["Mobile"],
    :crunchbase_url => "http://www.crunchbase.com/company/dropcam",
    :requisitions => [ { :name => "TODO",
                         :description => "TODO",
                         :skills => ["Python", "C", "iOS", "Android"],
                         :positions => [] } ] },
  { :name => "EdModo",
    :email => "chuck@edmodo.com",
    :contact_name => "Chuck Rosendahl", # Justin knows Annie, 2nd degree to someone in BD
    :url => "http://www.edmodo.com/",
    :description => "At Edmodo, our goal is to help educators around the world harness the power of social media to customize the classroom for each and every learner. ",
    :location => "San Mateo",
    :industries => ["Education"],
    :crunchbase_url => "http://www.crunchbase.com/company/edmodo",
    :requisitions => [ { :name => "TODO",
                         :description => "TODO",
                         :skills => ["PHP", "JavaScript"],
                         :positions => [] } ] },
  { :name => "Educreations",
    :email => "wade@educreations.com",
    :contact_name => "Wade Roberts", # Justin knows the LearnSprout guys, but not well
    :url => "http://www.educreations.com/",
    :description => "An online platform for creating and video video lectures",
    :misc => "Very early stage - founded by some bright developers, put a lot of focus on hiring technical folks",
    :location => "Sunnyvale",
    :industries => ["Education"],
    :crunchbase_url => "http://www.crunchbase.com/company/educreations" },
    :requisitions => [ { :name => "TODO",
                         :description => "TODO",
                         :skills => ["Python", "Django"],
                         :positions => [] } ] },
  { :name => "Education Elements",
    :email => "anthony@edelements.com",
    :contact_name => "Anthony Kim", # Kevin has Sharif
    :url => "http://edelements.com",
    :description => "Java hybrid education platform, curates material for k-12 charter schools",
    :misc => "Kevin is on good terms with CEO, and Sharif works there.",
    :location => "San Carlos",
    :industries => ["Education"],
    :crunchbase_url => "http://www.crunchbase.com/company/education-elements",
    :requisitions => [ { :name => "TODO",
                         :description => "TODO",
                         :skills => ["Java"],
                         :positions => [] } ] },
  { :name => "EngineYard",
    :email => "jdillon@engineyard.com",
    :contact_name => "John Dillon", # Justin has no connections
    :url => "http://www.engineyard.com/company/careers/software-developer",
    :description => "Primarily Ruby on Rails shop - interested in finding people who have large-scale distributed systems experience",
    :location => "SF",
    :industries => ["Infrastructure", "Consulting"],
    :crunchbase_url => "http://www.crunchbase.com/company/engineyard",
    :requisitions => [ { :name => "TODO",
                         :description => "TODO",
                         :skills => ["Ruby/Rails", "Java", "Python", "JavaScript"],
                         :positions => [] } ] },
  { :name => "Ephox C3",
    :email => "jack.mason@ephox.com",
    :contact_name => "Jack Mason", # Justin emailed Dave on 1/16/2013
    :url => "http://app.hawq.com/",
    :description => "The parent company isn't that exciting, but the startup they're going to spin off soon might be interesting. It's basically a crawler that checks corporate sites for errors. The team is in Australia and is unbelievably nice. They have a product lead in SF, and they're looking for an engineering lead (possible co-founder) to get things kicked off here. Since this is a spin-off and funded by the parent company, it can pay a real salary.",
    :misc => "Based in Australia, looking for a lead dev in SF. Really nice team. Kevin and I contract with them.",
    :location => "SF / remote",
    :industries => ["Utility"],
    :crunchbase_url => "http://www.crunchbase.com/company/ephox",
    :requisitions => [ { :name => "TODO",
                         :description => "TODO",
                         :skills => ["Ruby/Rails", "Backbone.js"],
                         :positions => [] } ] },
  { :name => "Experience Project",
    :email => "rohan@kanjoya.com",
    :contact_name => "Rohan Bhobe", # Justin has no connections
    :url => "http://www.experienceproject.com/",
    :description => "Blog site that is very touchy-feely and helps people connect - interesting social networking work",
    :misc => "Company operated by Kanjoya, lots of well-known investors and social mission",
    :location => "SF",
    :industries => ["Social"],
    :crunchbase_url => "http://www.crunchbase.com/company/experience-project",
    :requisitions => [ { :name => "TODO",
                         :description => "TODO",
                         :skills => ["PHP, Python, MySQL, Redis, Beanstalk, Node.js, Hadoop"],
                         :positions => [] } ] },
  { :name => "Flite",
    :email => "giles@flite.com",
    :contact_name => "Giles Goodwin", # Justin has no connections
    :url => "http://www.flite.com/",
    :description => "Slick, real-time ad platform - data analytics",
    :location => "SF",
    :industries => ["Advertising"],
    :crunchbase_url => "http://www.crunchbase.com/company/flite",
    :requisitions => [ { :name => "TODO",
                         :description => "TODO",
                         :skills => [ "Java", "Hadoop" ],
                         :positions => [] } ] },
  { :name => "Funzio",
    :email => "ken@funzio.com",
    :contact_name => "Ken Chiu", # Justin has no connections
    :url => "http://www.funzio.com/",
    :description => "Cross-platform social games.",
    :location => "SF",
    :industries => ["Gaming"],
    :crunchbase_url => "http://www.crunchbase.com/company/funzio",
    :requisitions => [ { :name => "TODO",
                         :description => "TODO",
                         :skills => [ "iOS", "Android", "Node.js", "Hadoop" ],
                         :positions => [] } ] },
  { :name => "GoodGuide",
    :email => "pedro@goodguide.com",
    :contact_name => "Pedro Viera", # Justin has no connections
    :url => "http://www.goodguide.com/about/jobs",
    :description => "An idea of cataloging consumer goods based on your own filters.",
    :misc => "Really want to see projects, will also accept front-end devs or experience with NLP/search algorithms ",
    :location => "SF",
    :industries => ["Commerce"],
    :crunchbase_url => "http://www.crunchbase.com/company/goodguide",
    :requisitions => [ { :name => "TODO",
                         :description => "TODO",
                         :skills => [ "Ruby/Rails", "Django", "Struts" ],
                         :positions => [] } ] },
  { :name => "Groupon",
    :email => "holden@groupon.com",
    :contact_name => "Jeff Holden", # Justin emailed Chris on 1/16/2013
    :url => "http://www.groupon.com/",
    :description => "Flash-sale deals",
    :location => "SF, PA",
    :industries => ["Commerce"],
    :crunchbase_url => "http://www.crunchbase.com/company/groupon-groupie",
    :requisitions => [ { :name => "TODO",
                         :description => "TODO",
                         :skills => [ "Java", "Hadoop", "Python" ],
                         :positions => [] } ] },
  { :name => "hearsaysocial",
    :email => "steve@hearsaysocial.com",
    :contact_name => "Steve Garrity", # Justin knows Bowen
    :url => "http://hearsaysocial.com/",
    :description => "Enterprise social sales and marketing",
    :location => "SF",
    :industries => ["Advertising"],
    :crunchbase_url => "http://www.crunchbase.com/company/hearsay-social",
    :requisitions => [ { :name => "TODO",
                         :description => "TODO",
                         :skills => [ "MapReduce", "RabbitMQ", "Python", "Django", "JavaScript" ],
                         :positions => [] } ] },
  { :name => "insightly",
    :email => "team@insightly.com",
    :contact_name => "Insightly Team", # Justin has no connections
    :url => "http://insight.ly/",
    :industries => [],
    :crunchbase_url => "http://www.crunchbase.com/company/insightly",
    :requisitions => [ { :name => "TODO",
                         :description => "TODO",
                         :skills => [".NET", "memcached", "JavaScript"],
                         :positions => [] } ] },
  { :name => "isocket",
    :email => "john@isocket.com",
    :contact_name => "John Ramey", # Justin emailed John on 1/16/2013
    :url => "https://www.isocket.com/",
    :description => "Direct-sold web ads.",
    :stack => [],
    :misc => "Justin has a contact there",
    :location => "MTV",
    :industries => ["Advertising"],
    :crunchbase_url => "http://www.crunchbase.com/company/isocket",
    :requisitions => [ { :name => "TODO",
                         :description => "TODO",
                         :skills => [],
                         :positions => [] } ] },
  { :name => "JobVite",
    :email => "adam@jobvite.com",
    :contact_name => "Adam Hyder", # Justin has no connections
    :url => "jobvite.com",
    :description => "Data Analytics, Social Plug-ins, In-house CRM",
    :location => "Burlingame. CA",
    :industries => ["Recruiting"],
    :crunchbase_url => "http://www.crunchbase.com/company/jobvite",
    :requisitions => [ { :name => "TODO",
                         :description => "TODO",
                         :skills => ["JavaScript", "AngularJS"],
                         :positions => [] } ] },
  { :name => "John McNeil Studio",
    :email => "john@johnmcneilstudio.com",
    :contact_name => "John McNeil", # Justin knows a handful of folks, will email after he's done contracting with them
    :url => "http://johnmcneilstudio.com/",
    :description => "Their website blows, but the company is actually really amazing. They have some beautiful studios over in Berkeley, maybe about 40 employees, and work with a lot of high-end clients (this gig is for http://www.toms.com/). They're looking for both full-time and contract work, starting ASAP. Since they're an agency they have varied stacks, but the position they're hiring for right now is RoR / JavaScript. Pay is exceptionally high, since it's a high-end agency.",
    :misc => "Beautiful studios, TDD, pair programming",
    :location => "Berkeley",
    :industries => ["Consulting"],
    :crunchbase_url => "http://www.crunchbase.com/company/blueprint-design-studio",
    :requisitions => [ { :name => "TODO",
                         :description => "TODO",
                         :skills => ["Ruby/Rails", "JavaScript"],
                         :positions => [] } ] },
  { :name => "Klout",
    :email => "binh@klout.com",
    :contact_name => "Binh Tran", # Justin has a weak 2nd deg to Felipe Oliveira 2nd, Lead Application Services Engineer
    :url => "http://klout.com/",
    :description => "Measures influence across social media sites.",
    :location => "SF",
    :industries => ["Social"],
    :crunchbase_url => "http://www.crunchbase.com/company/klout",
    :requisitions => [ { :name => "TODO",
                         :description => "TODO",
                         :skills => [ "C++", "Java", "MapReduce", "Hadoop", "Hive", "HBase", "Sqoop"],
                         :positions => [] } ] },
  { :name => "Lookout",
    :email => "team@lookout.com",
    :contact_name => "Lookout Team", # Tyler interned here, he probably has connections
    :url => "https://www.lookout.com/",
    :description => "Acquired by Microsoft. Mobile anti-virus and phone recovery",
    :location => "SF",
    :industries => ["Security"],
    :crunchbase_url => "http://www.crunchbase.com/company/lookout",
    :requisitions => [ { :name => "TODO",
                         :description => "TODO",
                         :skills => ["Java", "C", "iOS", "Android"],
                         :positions => [] } ] },
  { :name => "Lumos Labs",
    :email => "david@lumoslabs.com",
    :contact_name => "David Drescher", # Justin has no connections
    :url => "http://www.lumosity.com/",
    :description => "Brain-training games and software",
    :misc => "tdd and agile",
    :location => "SF",
    :industries => ["Gaming", "Education"],
    :crunchbase_url => "http://www.crunchbase.com/company/luminosity#",
    :requisitions => [ { :name => "TODO",
                         :description => "TODO",
                         :skills => ["Ruby/Rails", "JavaScript"],
                         :positions => [] } ] },
  { :name => "Medium",
    :email => "team@medium.com",
    :contact_name => "Medium Team", # Justin has no connections
    :url => "https://medium.com/",
    :description => "",
    :misc => "Offering absurdly high comp - $175k + equity",
    :requisitions => [ { :name => "TODO",
                         :description => "TODO",
                         :skills => ["Ruby/Rails", "JavaScript"],
                         :positions => [] } ] },
  { :name => "MetaMarkets",
    :email => "mike@metamarkets.com",
    :contact_name => "Mike Driscoll", # Justin and Kevin both interviewed
    :url => "metamarkets.com",
    :description => "Ad analytics for big data",
    :location => "SF",
    :industries => ["Advertising", "Analytics"],
    :crunchbase_url => "http://www.crunchbase.com/company/metamarkets",
    :requisitions => [ { :name => "TODO",
                         :description => "TODO",
                         :skills => ["JavaScript", "NoSQL"],
                         :positions => [] } ] },
  { :name => "Minerva Project",
    :email => "ben@minervaproject.com",
    :contact_name => "Ben Nelson", # DJ works here
    :url => "http://minervaproject.com",
    :description => "Online post-secondary institution aiming to be the Ivy League of online learning",
    :location => "SF",
    :industries => ["Education"],
    :crunchbase_url => "http://www.crunchbase.com/company/the-minerva-project",
    :requisitions => [ { :name => "TODO",
                         :description => "TODO",
                         :skills => ["Python"],
                         :positions => [] } ] },
  { :name => "ModCloth",
    :email => "eric@modcloth.com",
    :contact_name => "Eric Koger", # Justin knows Hannah
    :url => "http://www.modcloth.com/",
    :description => "Sells affordable independent designer fashion and decor.",
    :misc => "A little bit hipster.",
    :location => "Soma",
    :industries => ["Fashion"],
    :crunchbase_url => "http://www.crunchbase.com/company/modcloth",
    :requisitions => [ { :name => "TODO",
                         :description => "TODO",
                         :skills => ["Ruby/Rails", "MySQL"],
                         :positions => [] } ] },
  { :name => "New Relic",
    :email => "bjorn@newrelic.com",
    :contact_name => "Bjorn Freeman-Benson", # Justin has no connections
    :url => "http://newrelic.com/about/jobs",
    :description => "Deploy on New Relic - learn about your app",
    :location => "SF",
    :industries => ["Analytics", "Infrastructure"],
    :crunchbase_url => "http://www.crunchbase.com/company/newrelic",
    :requisitions => [ { :name => "TODO",
                         :description => "TODO",
                         :skills => ["Ruby/Rails"],
                         :positions => [] } ] },
  { :name => "Nextdoor",
    :email => "matt@nextdoor.com",
    :contact_name => "Matt Wise", # Justin has no connections
    :url => "https://nextdoor.com/",
    :description => "Private social network for neighbors",
    :location => "SF",
    :industries => ["Social"],
    :crunchbase_url => "http://www.crunchbase.com/company/nextdoor",
    :requisitions => [ { :name => "TODO",
                         :description => "TODO",
                         :skills => ["Python", "C++", "iOS", "Hadoop", "Hive", "Pig", "MapReduce"],
                         :positions => [] } ] },
  { :name => "Nomic",
    :email => "team@nomic.com",
    :contact_name => "Nomic Team", # Justin met their founder once
    :url => "http://www.nomic.com/",
    :description => "This small team of 8 (with 4 devs, dev founder) is aiming to capture relationships between businesses and their customers in a kind of LinkedIn-style way. They're on a RoR / mongodb / Backbone.js stack. Their founder is really chill, and after talking about their positioning and bigger plans I'm pretty sold on the quality of his idea.",
    :misc => "Super chill",
    :location => "Mission",
    :industries => ["Social"],
    :requisitions => [ { :name => "TODO",
                         :description => "TODO",
                         :skills => ["Node.js", "MongoDB", "Backbone.js"],
                         :positions => [] } ] },
  { :name => "OKCupid Labs",
    :email => "brian@okcupidlabs.com",
    :contact_name => "Brian Luerssen", # Justin has no connections
    :url => "",
    :description => "Experimenting with online dating",
    :location => "SF",
    :industries => ["Dating", "Social"],
    :crunchbase_url => "http://www.crunchbase.com/company/okcupid-labs",
    :requisitions => [ { :name => "TODO",
                         :description => "TODO",
                         :skills => ["Ruby/Rails"],
                         :positions => [] } ] },
  { :name => "okta",
    :email => "team@okta.com",
    :contact_name => "Okta Team", # Traunza knows a few people
    :url => "http://www.okta.com/",
    :description => "On-demand identity and access management",
    :location => "Soma",
    :industries => ["Security"],
    :crunchbase_url => "http://www.crunchbase.com/company/okta",
    :requisitions => [ { :name => "TODO",
                         :description => "TODO",
                         :skills => ["Java", ".NET", "iOS"],
                         :positions => [] } ] },
  { :name => "One King's Lane",
    :email => "ali@onekingslane.com",
    :contact_name => "Ali Pincus", # Justin will ask
    :url => "http://onekingslane.com",
    :description => "High-end home decor site, focus on event-based shopping and vintage goods curation.",
    :misc => "Pristine office, friendly team. Well-established.",
    :location => "Civic center",
    :industries => ["Commerce"],
    :crunchbase_url => "http://www.crunchbase.com/company/one-kings-lane",
    :requisitions => [ { :name => "TODO",
                         :description => "TODO",
                         :skills => ["Ruby/Rails", "iOS", "Android"],
                         :positions => [] } ] },
  { :name => "One Medical",
    :email => "mspolin@onemedical.com",
    :contact_name => "Mathew Spolin", # We have a contract with them
    :url => "http://www.onemedical.com/jobs",
    :description => "Low cost primary care service providers - currently just building out in major cities but have plans to expand",
    :location => "SF",
    :industries => ["Medical"],
    :crunchbase_url => "http://www.crunchbase.com/company/one-medical-group-2" },
    :requisitions => [ { :name => "TODO",
                         :description => "TODO",
                         :skills => ["Ruby/Rails"],
                         :positions => [] } ] },
  { :name => "Ooyala",
    :email => "sean@ooyala.com",
    :contact_name => "Sean Knapp", # Justin has no connections
    :url => "http://www.ooyala.com/",
    :description => "Targeted video ads.",
    :industries => ["Advertising"],
    :crunchbase_url => "http://www.crunchbase.com/company/ooyala",
    :requisitions => [ { :name => "TODO",
                         :description => "TODO",
                         :skills => [],
                         :positions => [] } ] },
  { :name => "opendns",
    :email => "david@opendns.com",
    :contact_name => "David Ulevitch",
    :url => "http://www.opendns.com/",
    :description => "Tricked out dns solution", # Justin has no connections
    :stack => ["c, c++, c#, php, javascript"],
    :misc => "",
    :location => "SF",
    :industries => ["Infrastructure"],
    :crunchbase_url => "http://www.crunchbase.com/company/opendns",
    :requisitions => [ { :name => "TODO",
                         :description => "TODO",
                         :skills => ["C", "C++", "C#", "PHP", "JavaScript"],
                         :positions => [] } ] },
  { :name => "OPower",
    :email => "rick.mchphee@opower.com",
    :contact_name => "Rick McPhee", # Justin has no connections
    :url => "www.opower.com",
    :description => "Energy efficiency company that measures and reports usage data",
    :location => "SF",
    :industries => ["Energy"],
    :crunchbase_url => "http://www.crunchbase.com/company/opower",
    :requisitions => [ { :name => "TODO",
                         :description => "TODO",
                         :skills => ["Java", "Ruby/Rails", "SQL"],
                         :positions => [] } ] },
  { :name => "Organizer",
    :email => "ralph@organizer.com",
    :contact_name => "Ralph Garvin",
    :url => "http://www.organizer.com/", # Justin has no connections
    :description => "Electionear is Organizer's first mobile app for political campaigns and advocacy organizations of any size. It lets you have high-impact conversations with voters and constituents without wasting precious time and money in the process.",
    :location => "Civic center",
    :industries => ["Social", "Political"],
    :crunchbase_url => "http://www.crunchbase.com/company/organic",
    :requisitions => [ { :name => "TODO",
                         :description => "TODO",
                         :skills => ["Java", "GWT", "iOS", "Android"],
                         :positions => [] } ] },
  { :name => "Peel",
    :email => "bala@peel.com",
    :contact_name => "Bala Krishnan", # Justin has no connections
    :url => "http://www.peel.com",
    :description => "An iOS/Android app that curates TV content.  Doing interesting things with ML and data science.",
    :misc => "closed $16M B round",
    :location => "MV",
    :industries => ["Mobile", "Entertainment"],
    :crunchbase_url => "http://www.crunchbase.com/company/peel",
    :requisitions => [ { :name => "TODO",
                         :description => "TODO",
                         :skills => ["ios", "android"],
                         :positions => [] } ] },
  { :name => "Picarro",
    :email => "eric@picarro.com",
    :contact_name => "Eric Crosson", # Justin has no connections
    :url => "http://www.picarro.com/",
    :description => "Ultra-high performance greenhouse gas and environmental analyzers",
    :location => "Santa Clara",
    :industries => ["Energy"],
    :crunchbase_url => "http://www.crunchbase.com/company/picarro" },
    :requisitions => [ { :name => "TODO",
                         :description => "TODO",
                         :skills => ["Node.js", "MongoDB", "Python"],
                         :positions => [] } ] },
  { :name => "Pivotal Labs",
    :email => "rob@pivotallabs.com",
    :contact_name => "Rob Mee", # Justin emailed Heisterkamp on 1/16/2013
    :url => "https://pivotallabs.com",
    :description => "Rub-on-Rails contracting shop. ",
    :misc => "Bought by EMC with plans to scale to a larger size and put more focus into Pivotal Tracker",
    :location => "SF",
    :industries => ["Consulting"],
    :crunchbase_url => "http://www.crunchbase.com/company/pivotal-labs",
    :requisitions => [ { :name => "TODO",
                         :description => "TODO",
                         :skills => ["Ruby/Rails"],
                         :positions => [] } ] },
  { :name => "Platfora",
    :email => "john@platfora.com",
    :contact_name => "John Eshelman", # Justin has several 2nd-degree connections
    :url => "http://www.platfora.com",
    :description => "Interactive, In-Memory Business Intelligence",
    :misc => "Just received B round - $20M+",
    :location => "San Mateo",
    :industries => ["Infrastructure", "Analytics"],
    :crunchbase_url => "http://www.crunchbase.com/company/platfora",
    :requisitions => [ { :name => "TODO",
                         :description => "TODO",
                         :skills => ["Java", "Hadoop"],
                         :positions => [] } ] },
  { :name => "Playnomics",
    :email => "team@playnomics.com",
    :contact_name => "Playnomics Team", # Justin has no connections
    :url => "http://www.playnomics.com/",
    :description => "for Hadoop.",
    :location => "SF",
    :industries => ["Gaming"],
    :crunchbase_url => "http://www.crunchbase.com/company/playnomics",
    :requisitions => [ { :name => "TODO",
                         :description => "TODO",
                         :skills => ["Java", "SQL", "Hadoop", "Hive", "JavaScript"],
                         :positions => [] } ] },
  { :name => "PocketGems",
    :email => "harlan@pocketgems.com",
    :contact_name => "Harlan Crystal", # Code2040 can probably introduce us
    :url => "http://pocketgems.com/jobs/explore",
    :description => "Mobile gaming company",
    :location => "SF",
    :industries => ["Gaming"],
    :crunchbase_url => "http://www.crunchbase.com/company/pocket-gems",
    :requisitions => [ { :name => "TODO",
                         :description => "TODO",
                         :skills => ["iOS", "Android", "Python"],
                         :positions => [] } ] },
  { :name => "Polyvore",
    :email => "pasha@polyvore.com",
    :contact_name => "Pasha Sadri",
    :url => "http://www.polyvore.com/",
    :description => "Designers and people post items online, and then users can make/share outfits with those items.",
    :location => "MTV",
    :industries => ["Fashion"],
    :crunchbase_url => "http://www.crunchbase.com/company/polyvore",
    :requisitions => [ { :name => "TODO",
                         :description => "TODO",
                         :skills => ["MySQL", "Memcached", "Nginx", "RabbitMQ", "Give", "AWS", "Splunk"],
                         :positions => [] } ] },
  { :name => "Pure Storage",
    :email => "coz@purestorage.com",
    :contact_name => "John Cozgrove", # Justin knows their CFO and office manager
    :url => "http://www.purestorage.com/",
    :description => "Pure Storage has a simple mission: to enable the widespread adoption of flash in the enterprise data center.",
    :location => "MTV",
    :industries => ["Infrastructure"],
    :crunchbase_url => "http://www.crunchbase.com/company/pure-storage",
    :requisitions => [ { :name => "TODO",
                         :description => "TODO",
                         :skills => ["C", "C++"],
                         :positions => [] } ] },
  { :name => "Rally",
    :email => "brian@rally.org",
    :contact_name => "Brian Upton", # Alex and JJ
    :url => "https://rally.org/",
    :description => "Basically the same as kickstarter, with a more social slant.",
    :location => "Soma",
    :industries => ["Social", "Political"],
    :crunchbase_url => "http://www.crunchbase.com/company/rally-org",
    :requisitions => [ { :name => "TODO",
                         :description => "TODO",
                         :skills => ["Ruby/Rails"],
                         :positions => [] } ] },
  { :name => "raptr",
    :email => "dave@raptr.com",
    :contact_name => "Dave Swenson", # Ra may be able to intro, Justin has no other connections
    :url => "http://raptr.com/",
    :description => "Social network built around gaming",
    :stack => ["python, php, qt"],
    :misc => "",
    :location => "MTV",
    :industries => ["Gaming"],
    :crunchbase_url => "http://www.crunchbase.com/company/raptr",
    :requisitions => [ { :name => "TODO",
                         :description => "TODO",
                         :skills => ["Python", "PHP", "QT"],
                         :positions => [] } ] },
  { :name => "shopkick",
    :email => "aaron@shopkick.com",
    :contact_name => "Aaron Emigh", # Justin has no connections
    :url => "http://www.shopkick.com/",
    :description => "Rewards program tied to your credit card",
    :location => "PA",
    :industries => ["Commerce"],
    :crunchbase_url => "http://www.crunchbase.com/company/shopkick",
    :requisitions => [ { :name => "TODO",
                         :description => "TODO",
                         :skills => ["MapReduce", "Hadoop", "ActiveMQ", "Thrift", "Python", "Pylons"],
                         :positions => [] } ] },
  { :name => "smule",
    :email => "ge@smule.com",
    :contact_name => "Ge Wang", # Justin has no connections
    :url => "http://www.smule.com/",
    :description => "Social music apps",
    :location => "SF, PA",
    :industries => ["Music", "Social"],
    :crunchbase_url => "http://www.crunchbase.com/company/smule",
    :requisitions => [ { :name => "TODO",
                         :description => "TODO",
                         :skills => ["Ruby/Rails", "Flash", "Java", "iOS", "Android"],
                         :positions => [] } ] },
  { :name => "Spongecell",
    :email => "chris@spongecell.com",
    :contact_name => "Chris Hobbs",
    :url => "http://www.spongecell.com/", # Kyle may know someone?
    :description => "HTML5 rich-media ads.",
    :stack => ["node.js, ror, redis, html5, big data"],
    :misc => "HQ in NY, but building out SF. Looking for sr software engineer",
    :location => "Civic center",
    :industries => ["Advertising"],
    :crunchbase_url => "http://www.crunchbase.com/company/spongecell",
    :requisitions => [ { :name => "TODO",
                         :description => "TODO",
                         :skills => ["Ruby/Rails", "Redis", "HTML5", "Node.js"],
                         :positions => [] } ] },
  { :name => "Stitch Fix",
    :email => "katrina@stitchfix.com",
    :contact_name => "Katrina Lake",
    :url => "http://stitchfixjobs.com/",
    :description => "Stitch Fix is an early stage startup building a disruptive, data-driven, retail platform. We have gobs of paying customers and things are growing fast. We're currently a small, senior dev & analytics team based in SF - but we'd like to add some more talented folks. ",
    :location => "SF",
    :industries => ["Commerce", "Analytics"],
    :crunchbase_url => "http://www.crunchbase.com/company/stitch-fix" },
    :requisitions => [ { :name => "TODO",
                         :description => "TODO",
                         :skills => ["Ruby", "Python", "R", "PSQL"],
                         :positions => [] } ] },
  { :name => "Sumo Logic",
    :email => "christian@sumologic.com",
    :contact_name => "Christian Beedgen",
    :url => "http://www.sumologic.com/",
    :description => "Analytics from log processing.",
    :stack => ["big data"],
    :misc => "Zack works here",
    :location => "MTV",
    :industries => ["Infrastructure"],
    :crunchbase_url => "http://www.crunchbase.com/company/sumo-logic",
    :requisitions => [ { :name => "TODO",
                         :description => "TODO",
                         :skills => [],
                         :positions => [] } ] },
  { :name => "Syntellia",
    :email => "kostas@syntellia.com",
    :contact_name => "Kostas Eleftheriou",
    :url => "http://syntellia.com/#0",
    :description => "Makes the fleksy keyboard app, which is good for typing without looking, or for the visually impaired.",
    :stack => ["mobile"],
    :misc => "Just raised $900k through some miracle.",
    :industries => ["Utility"],
    :crunchbase_url => "http://www.crunchbase.com/company/syntellia" },
    :requisitions => [ { :name => "TODO",
                         :description => "TODO",
                         :skills => [],
                         :positions => [] } ] },
  { :name => "Tagged",
    :email => "Johann@tagged.com",
    :contact_name => "Johann Schleier-Smith",
    :url => "http://www.tagged.com/?",
    :description => "Social network for meeting new people, gaming, analytics",
    :location => "SF",
    :industries => ["Social", "Gaming"],
    :crunchbase_url => "http://www.crunchbase.com/company/tagged",
    :requisitions => [ { :name => "TODO",
                         :description => "TODO",
                         :skills => [],
                         :positions => [] } ] },
  { :name => "TellApart",
    :email => "julie@tellapart.com",
    :contact_name => "Julie Black",
    :url => "http://tellapart.com/",
    :description => "TellApart Transactional Retargeting helps bring visitors back through the use of dynamic, personalized banner ads which show your products to the right visitors.  Simply put, it turns lost shoppers into return customers.",
    :location => "Burlingame",
    :industries => ["Advertising"],
    :crunchbase_url => "http://www.crunchbase.com/company/tellapart",
    :requisitions => [ { :name => "TODO",
                         :description => "TODO",
                         :skills => ["Java", "Python", "C++"],
                         :positions => [] } ] },
  { :name => "Threadflip",
    :email => "jeff@threadflip.com",
    :contact_name => "Jeff Shiau",
    :url => "http://www.threadflip.com/home",
    :description => "Threadflip is a social marketplace for buying, selling, and discovering new, unique, and pre-loved fashion",
    :location => "SF",
    :industries => ["Commerce", "Social", "Fashion"],
    :crunchbase_url => "http://www.crunchbase.com/company/threadflip",
    :requisitions => [ { :name => "TODO",
                         :description => "TODO",
                         :skills => ["Ruby/Rails"],
                         :positions => [] } ] },
  { :name => "Twitch.tv",
    :email => "Justin@twitch.tv",
    :contact_name => "Justin Kan",
    :url => "http://www.twitch.tv",
    :description => "We're building the world's largest video platform and community for gamers, and we're looking for smart, passionate people to help us do it.",
    :industries => ["Gaming"],
    :crunchbase_url => "http://www.crunchbase.com/company/twitch",
    :requisitions => [ { :name => "TODO",
                         :description => "TODO",
                         :skills => ["Ruby/Rails", "PostgreSQL", "MongoDB", "Nginx"],
                         :positions => [] } ] },
  { :name => "Typesafe",
    :email => "jonas@typesafe.com",
    :contact_name => "Jonas Boner",
    :url => "http://typesafe.com/",
    :description => "Typesafe makes it easy to build software based on the open source Scala programming language, Akka middleware, and Play web framework. From multicore to cloud computing, it's purpose built for scale.",
    :location => "SF",
    :industries => ["Infrastructure"],
    :crunchbase_url => "http://www.crunchbase.com/company/typesafe",
    :requisitions => [ { :name => "TODO",
                         :description => "TODO",
                         :skills => ["Scala", "Java"],
                         :positions => [] } ] },
  { :name => "Udacity",
    :email => "mike@udacity.com",
    :contact_name => "Mike Sokolsky",
    :url => "http://www.udacity.com/",
    :description => "Free online higher education courses.",
    :location => "PA",
    :industries => ["Education"],
    :crunchbase_url => "http://www.crunchbase.com/company/udacity",
    :requisitions => [ { :name => "TODO",
                         :description => "TODO",
                         :skills => ["Python"],
                         :positions => [] } ] },
  { :name => "Yelp",
    :email => "stop@yelp.com",
    :contact_name => "Michael Stoppelman",
    :url => "http://www.yelp.com/careers",
    :description => "Review everything and find it near you on a map.",
    :misc => "Desperate",
    :location => "sf",
    :industries => ["Commerce", "Social"],
    :crunchbase_url => "http://www.crunchbase.com/company/yelp",
    :requisitions => [ { :name => "TODO",
                         :description => "TODO",
                         :skills => ["Python"],
                         :positions => [] } ] },
  { :name => "zendesk",
    :email => "morten@zendesk.com",
    :contact_name => "Morten Primdahl",
    :url => "http://www.zendesk.com/",
    :description => "Customer support software",
    :location => "Civic center",
    :industries => ["Utility"],
    :crunchbase_url => "http://www.crunchbase.com/company/zendesk",
    :requisitions => [ { :name => "TODO",
                         :description => "TODO",
                         :skills => ["Ruby/Rails"],
                         :positions => [] } ] },
  { :name => "Zynga",
    :email => "cadir@zynga.com",
    :contact_name => "Cadir Lee",
    :url => "http://zynga.com/",
    :description => "Facebook and mobile games",
    :location => "Potrero",
    :industries => ["Gaming", "Social"],
    :crunchbase_url => "http://www.crunchbase.com/company/zynga",
    :requisitions => [ { :name => "TODO",
                         :description => "TODO",
                         :skills => ["C", "C++", "Java", "Python", "iOS", "Android"],
                         :positions => [] } ] } ]


# COMPANIES TO ADD
# Origami Logic
# LearnSprout (Justin kinda knows their founding team)
# Level Up Analytics (Justin knows Anu)
# Iridescent (Justin knows Anu)
# Square (Justin emailed Heisterkamp on 1/16/2013)

companies.each do |company_data|
  puts "Creating #{company_data[:name]}..."
  industry_tags = company_data[:industries].map(&tag_proc)
  company = Company.new(:name => company_data[:name],
                        :email => company_data[:email],
                        :description => company_data[:description],
                        :size => company_data[:size],
                        :dev_team_size => company_data[:dev_team_size],
                        :industries => industry_tags)
  company.company_tags.each do |company_tag|
    company_tag.company = company
  end
  company.save!

  next if company_data[:requsitions].nil?

  company_data[:requisitions].each do |requisition_data|
    skill_tags = requisition_data[:skills].map(&tag_proc)
    position_tags = requisition_data[:positions].map(&tag_proc)
    requisition = Requisition.new(:company => company,
                                  :name => requisition_data[:name],
                                  :skills => skill_tags,
                                  :positions => position_tags)
    requisition.requisition_tags.each do |requisition_tag|
      requisition_tag.requisition = requisition
    end
    requisition.save!

    interest_decision = InterestDecision.create!(:requisition => requisition, :user => user)
  end
end

